### PR TITLE
scalable svg

### PR DESCRIPTION
**Pull request by mix3d**
by using the viewBox parameter instead of directly setting width and height, the svg can scale cleanly to any size display. 
This backwards compatible change would default to the same behavior, but also either set a defined pixel size of the users choice, or 'auto'/-1 to not include the width/height, making the svg scale to 100% of the parent width.

### CODE REVIEW

**Comment by ahwayakchih** [comment]
@mix3d what if, instead of adding third argument (`displaySize`), SVG renderer would just check if `cellSize` is anything else than `0`? If it's `0`, then it would set cell size to default, but render scalable SVG. Otherwise, it would render as usual.
I mean, there's not much point in changing `cellSize` when result is fully scalable, right?
Problem is that it could break older code, where someone was calling without arguments but counted on `width` and `height` in the output.

**Comment by mix3d** [comment]
I'd rather have it be semantically intuitive, and use `'auto'` instead of -1, but would be happy to make that change

**Comment by ahwayakchih** [comment]
Yeah, that could work too. Or maybe some symbol/const exported by library? So internally it would stay numeric type, but user could call something like:
```js
var svg = qr.createSvgTag(qr.scalable);
```

**Comment by ahwayakchih** [comment]
Of course that's just my point of view, and i'm not the one who can make final decision on this :).

@kazuhikoarase any thoughts on this?

**Comment by kazuhikoarase** [comment]
I merged it with develop branch and tried to refactor.
Will this help you?

https://github.com/kazuhikoarase/qrcode-generator/commit/633a0d3b5de6f6fa90cd2c6fffc0035621b7fa91

**Comment by ahwayakchih** [comment]
Yes, having `options` object gives us some space for any other extensions in the future.

Thanks!

**Comment by mix3d** [comment]
Downside is that it's a breaking change for existing users, but a much
cleaner approachb moving forward

**Comment by ahwayakchih** [comment]
@mix3d how is the change breaking? `options` object was not supported before, so only new code will use it. "Old" `cellSize, margin` signature is still supported as it was before AFAIK.

**Comment by mix3d** [comment]
Ah, I missed the part in the diff where the function was overloaded. Never
mind!

**Pull request merged**
